### ISSUE TITLE
NoSQL Databases

### ISSUE THREAD

**Issue by ueg1990** [rxin/db-readings#18]
Hello,

Sorry if this is the wrong place for suggestions. I was hoping if you can a chance to post reading for NoSQL Databases, something similar to one of you topics: "Essentials of Relational Databases". You have already added the Amazon Dynamo paper; it would be great to have more readings based on design and concepts behind NoSQL databases. 

Thank you :)

**Comment by rxin** [comment]
Thanks for the comment. Are there any specific examples you'd recommend?

My understanding is that the world is in coming around from "NoSQL". Everybody is adding SQL and stronger consistency/transactional semantics back. As a result, I'm not sure if there are any papers worth reading about "NoSQL" itself.  We could definitely add some about distributed consistency, an area this reading list is not yet covering well.

**Comment by ueg1990** [comment]
that would be cool too. thank you.
