### ISSUE TITLE
Sigmod2018 industrial list

### ISSUE THREAD

**Issue by goungoun** [rxin/db-readings#29]
@rxin, I found some interesting industrial papers on Sigmod 2018. https://sigmod2018.org/sigmod_industrial_list.shtml

- Amazon Aurora: On Avoiding Distributed Consensus for I/Os, Commits, and Membership Changes
- Cypher: An Evolving Query Language for Property Graphs
- Pinot: Realtime OLAP for 530 Million Users
- Apache Calcite: A Foundational Framework for Optimized Query Processing Over Heterogeneous Data Sources
- Structured Streaming: A Declarative API for Real-Time Applications in Apache Spark (<= your paper)

**Comment by rxin** [comment]
I probably wouldn't add most of them.
