### ISSUE TITLE
bug: Link to Berkley PhD readings not working

### ISSUE THREAD

**Issue by Silemo** [rxin/db-readings#38]
# Bug
The following link: [http://www.eecs.berkeley.edu/GradAffairs/CS/Prelims/db.html](http://www.eecs.berkeley.edu/GradAffairs/CS/Prelims/db.html) does not return any content (404 - Content not found).

# Proposed change
Remove this link from the ReadMe or update it with a valid one.

**Comment by Silemo** [comment]
Bug at line 104 of ReadMe.md:

`Berkeley [PhD prelim exam reading list](http://www.eecs.berkeley.edu/GradAffairs/CS/Prelims/db.html)`

**Comment by fisheuler** [comment]
It seemed the page have moved to this Google Doc : https://docs.google.com/spreadsheets/d/1QOf6UmSo87hELSZiDZZ3rSZngsh4CBcef06x-JkvCnI/edit?gid=652684559#gid=652684559, maybe we can use this address.

**Comment by rxin** [comment]
Thanks for fixing it, @fisheuler.
